/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Message {
  'text' : string,
  'sender' : string,
  'timestamp' : bigint,
}
export type ProjectBudgetRange = { 'range50_100kNOK' : null } |
  { 'range10_50kNOK' : null } |
  { 'range1_10kNOK' : null } |
  { 'range100kPlusNOK' : null };
export type ProjectStatus = { 'new' : null } |
  { 'completed' : null } |
  { 'followup' : null } |
  { 'reviewed' : null } |
  { 'inProgress' : null };
export interface ProjectSubmission {
  'id' : bigint,
  'files' : Array<ExternalBlob>,
  'status' : ProjectStatus,
  'deliveryDescription' : [] | [string],
  'clientName' : string,
  'messages' : Array<Message>,
  'projectDescription' : string,
  'submittedBy' : Principal,
  'deliveryLink' : [] | [string],
  'email' : string,
  'statusComment' : [] | [string],
  'timestamp' : bigint,
  'companyName' : string,
  'budget' : ProjectBudgetRange,
  'timeline' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDeliveryLink' : ActorMethod<[bigint, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserProfile' : ActorMethod<[UserProfile], undefined>,
  'getAllMessages' : ActorMethod<[], Array<[bigint, Array<Message>]>>,
  'getAllSubmissions' : ActorMethod<[], Array<ProjectSubmission>>,
  'getAllUserMessages' : ActorMethod<[], Array<[bigint, Array<Message>]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProjectFiles' : ActorMethod<[bigint], Array<ExternalBlob>>,
  'getProjectMessages' : ActorMethod<[bigint], Array<Message>>,
  'getSubmission' : ActorMethod<[bigint], ProjectSubmission>,
  'getSubmissionsByClient' : ActorMethod<[string], Array<ProjectSubmission>>,
  'getSubmissionsByStatus' : ActorMethod<
    [ProjectStatus],
    Array<ProjectSubmission>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjects' : ActorMethod<[], Array<ProjectSubmission>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsCompleted' : ActorMethod<[bigint, [] | [string]], undefined>,
  'markAsFollowup' : ActorMethod<[bigint, [] | [string]], undefined>,
  'markAsInProgress' : ActorMethod<[bigint, [] | [string]], undefined>,
  'markAsReviewed' : ActorMethod<[bigint, [] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string, string], undefined>,
  'submitAuthenticatedProject' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      ProjectBudgetRange,
      Array<ExternalBlob>,
    ],
    { 'projectId' : bigint, 'timestamp' : bigint }
  >,
  'submitProject' : ActorMethod<
    [string, string, string, string, string, ProjectBudgetRange],
    { 'projectId' : bigint, 'timestamp' : bigint }
  >,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];