/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
});
export const Message = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProjectStatus = IDL.Variant({
  'new' : IDL.Null,
  'completed' : IDL.Null,
  'followup' : IDL.Null,
  'reviewed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ProjectBudgetRange = IDL.Variant({
  'range50_100kNOK' : IDL.Null,
  'range10_50kNOK' : IDL.Null,
  'range1_10kNOK' : IDL.Null,
  'range100kPlusNOK' : IDL.Null,
});
export const ProjectSubmission = IDL.Record({
  'id' : IDL.Nat,
  'files' : IDL.Vec(ExternalBlob),
  'status' : ProjectStatus,
  'deliveryDescription' : IDL.Opt(IDL.Text),
  'clientName' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'projectDescription' : IDL.Text,
  'submittedBy' : IDL.Principal,
  'deliveryLink' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'statusComment' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'companyName' : IDL.Text,
  'budget' : ProjectBudgetRange,
  'timeline' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDeliveryLink' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfile' : IDL.Func([UserProfile], [], []),
  'getAllMessages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(Message)))],
      ['query'],
    ),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ProjectSubmission)], ['query']),
  'getAllUserMessages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(Message)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProjectFiles' : IDL.Func([IDL.Nat], [IDL.Vec(ExternalBlob)], ['query']),
  'getProjectMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getSubmission' : IDL.Func([IDL.Nat], [ProjectSubmission], ['query']),
  'getSubmissionsByClient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProjectSubmission)],
      ['query'],
    ),
  'getSubmissionsByStatus' : IDL.Func(
      [ProjectStatus],
      [IDL.Vec(ProjectSubmission)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjects' : IDL.Func([], [IDL.Vec(ProjectSubmission)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsCompleted' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'markAsFollowup' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'markAsInProgress' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'markAsReviewed' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'submitAuthenticatedProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ProjectBudgetRange,
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Record({ 'projectId' : IDL.Nat, 'timestamp' : IDL.Int })],
      [],
    ),
  'submitProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ProjectBudgetRange],
      [IDL.Record({ 'projectId' : IDL.Nat, 'timestamp' : IDL.Int })],
      [],
    ),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
  });
  const Message = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProjectStatus = IDL.Variant({
    'new' : IDL.Null,
    'completed' : IDL.Null,
    'followup' : IDL.Null,
    'reviewed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ProjectBudgetRange = IDL.Variant({
    'range50_100kNOK' : IDL.Null,
    'range10_50kNOK' : IDL.Null,
    'range1_10kNOK' : IDL.Null,
    'range100kPlusNOK' : IDL.Null,
  });
  const ProjectSubmission = IDL.Record({
    'id' : IDL.Nat,
    'files' : IDL.Vec(ExternalBlob),
    'status' : ProjectStatus,
    'deliveryDescription' : IDL.Opt(IDL.Text),
    'clientName' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'projectDescription' : IDL.Text,
    'submittedBy' : IDL.Principal,
    'deliveryLink' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'statusComment' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'companyName' : IDL.Text,
    'budget' : ProjectBudgetRange,
    'timeline' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDeliveryLink' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfile' : IDL.Func([UserProfile], [], []),
    'getAllMessages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(Message)))],
        ['query'],
      ),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ProjectSubmission)], ['query']),
    'getAllUserMessages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(Message)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProjectFiles' : IDL.Func([IDL.Nat], [IDL.Vec(ExternalBlob)], ['query']),
    'getProjectMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getSubmission' : IDL.Func([IDL.Nat], [ProjectSubmission], ['query']),
    'getSubmissionsByClient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProjectSubmission)],
        ['query'],
      ),
    'getSubmissionsByStatus' : IDL.Func(
        [ProjectStatus],
        [IDL.Vec(ProjectSubmission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjects' : IDL.Func([], [IDL.Vec(ProjectSubmission)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsCompleted' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'markAsFollowup' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'markAsInProgress' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'markAsReviewed' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'submitAuthenticatedProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ProjectBudgetRange,
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Record({ 'projectId' : IDL.Nat, 'timestamp' : IDL.Int })],
        [],
      ),
    'submitProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ProjectBudgetRange],
        [IDL.Record({ 'projectId' : IDL.Nat, 'timestamp' : IDL.Int })],
        [],
      ),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };